version: '3.8'

services:
  webapp:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: aspnetmvc_webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=postgres
    networks:
      - appnetwork

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres_data:
